Repository Life-Pill/pharmacy-pos-main-backend, pull requests merged in 2024-04, with the labels that each got.

#57 Resolve Order Handling Issues and Enhance Cashier Retrieval by Role
  pos-system/src/main/java/com/lifepill/possystem/controller/CashierController.java
  pos-system/src/main/java/com/lifepill/possystem/entity/enums/Role.java
  pos-system/src/main/java/com/lifepill/possystem/repo/cashierRepo/CashierRepo.java
  pos-system/src/main/java/com/lifepill/possystem/service/CashierService.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/CashierServiceIMPL.java
Labels: bug, enhancement, database enchancement, BugFIxed

#58 Implement JPA Auditing for Entity Tracking
  pos-system/src/main/java/com/lifepill/possystem/PosSystemApplication.java
  pos-system/src/main/java/com/lifepill/possystem/audit/AuditAwareImpl.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/ItemSaveRequestCategoryDTO.java
  pos-system/src/main/java/com/lifepill/possystem/exception/InsufficientItemQuantityException.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/ItemServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/OrderServiceIMPL.java
Labels: enhancement, BugFIxed

#59 Refactor Cashier to Employer Entity and Unit testing
  pos-system/SQL_Queries/cashier.sql
  pos-system/SQL_Queries/cashierbankdetails.sql
  pos-system/SQL_Queries/order.sql
  pos-system/src/main/java/com/lifepill/possystem/config/ProjectConfigSecurity.java
  pos-system/src/main/java/com/lifepill/possystem/controller/BranchController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/EmployerController.java
  pos-system/src/main/java/com/lifepill/possystem/dto/EmployerDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/EmployerWithoutImageDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/CashierUpdate/CashierPasswordResetDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/CashierUpdate/CashierUpdateDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/EmployerUpdate/EmployerAllDetailsUpdateDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/EmployerUpdate/EmployerPasswordResetDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/EmployerUpdate/EmployerRecentPinUpdateDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/EmployerUpdate/EmployerUpdateAccountDetailsDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/EmployerUpdate/EmployerUpdateBankAccountDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/EmployerUpdate/EmployerUpdateDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/RequestOrderSaveDTO.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Branch.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Cashier.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Employer.java
  pos-system/src/main/java/com/lifepill/possystem/entity/EmployerBankDetails.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Order.java
  pos-system/src/main/java/com/lifepill/possystem/repo/branchRepository/BranchRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/cashierRepo/CashierRepo.java
  pos-system/src/main/java/com/lifepill/possystem/repo/employerRepository/EmployerBankDetailsRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/employerRepository/EmployerRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/itemRepository/ItemCategoryRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/itemRepository/ItemRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/orderRepository/OrderDetailsRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/orderRepository/OrderRepository.java
  pos-system/src/main/java/com/lifepill/possystem/service/CashierService.java
  pos-system/src/main/java/com/lifepill/possystem/service/EmployerService.java
  pos-system/src/main/java/com/lifepill/possystem/service/ItemService.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/BranchServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/CashierServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/EmployerServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/ItemServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/OrderServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/SupplierServiceIMPL.java
  pos-system/src/test/java/com/lifepill/possystem/controller/CashierControllerTests.java
  pos-system/src/test/java/com/lifepill/possystem/controller/EmployerControllerTests.java
  pos-system/src/test/java/com/lifepill/possystem/repo/CashierRepoTests.java
  pos-system/src/test/java/com/lifepill/possystem/repo/EmployerRepositoryTests.java
Labels: enhancement, database enchancement, BugFIxed

#66 Create README.md
  README.md
Labels: documentation, database enchancement

#69 Modify Login Response to Include Employer Details and Set Active Status
  pos-system/src/main/java/com/lifepill/possystem/config/SecurityConfiguration.java
  pos-system/src/main/java/com/lifepill/possystem/config/SwaggerConfig.java
  pos-system/src/main/java/com/lifepill/possystem/controller/AuthController.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/AuthenticationResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/EmployerAuthDetailsResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/exception/AuthenticationException.java
  pos-system/src/main/java/com/lifepill/possystem/helper/ActiveStatusHelper.java
  pos-system/src/main/java/com/lifepill/possystem/service/AuthService.java
  pos-system/src/main/java/com/lifepill/possystem/service/EmployerService.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/AuthServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/EmployerServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/util/AuthUtils.java
  pos-system/src/main/resources/application.yml
Labels: bug, enhancement, BugFIxed

#73 Update Item Details in Order Service Implementation
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/RequestOrderDetailsSaveDTO.java
  pos-system/src/main/java/com/lifepill/possystem/entity/OrderDetails.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/OrderServiceIMPL.java
Labels: enhancement, database enchancement, BugFIxed

#74 Fix StackOverflowError in Hibernate QueryParameters
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/RequestOrderSaveDTO.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Order.java
  pos-system/src/main/java/com/lifepill/possystem/entity/PaymentDetails.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/OrderServiceIMPL.java
Labels: enhancement, database enchancement, BugFIxed

#75 Bug Fix - Total Amount Calculation in OrderDetails Entity
  pos-system/src/main/java/com/lifepill/possystem/entity/OrderDetails.java
Labels: database enchancement, BugFIxed

#76 Update Branch Summary Controller and Service with Unit and API Tests
  pos-system/pom.xml
  pos-system/src/main/java/com/lifepill/possystem/PosSystemApplication.java
  pos-system/src/main/java/com/lifepill/possystem/config/SecurityConfiguration.java
  pos-system/src/main/java/com/lifepill/possystem/controller/BranchController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/BranchSummaryController.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/RequestOrderDetailsSaveDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/PharmacyBranchResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Authority.java
  pos-system/src/main/java/com/lifepill/possystem/repo/employerRepository/EmployerRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/orderRepository/OrderDetailsRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/orderRepository/OrderRepository.java
  pos-system/src/main/java/com/lifepill/possystem/service/BranchService.java
  pos-system/src/main/java/com/lifepill/possystem/service/BranchSummaryService.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/BranchServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/BranchSummaryServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/OrderServiceIMPL.java
  pos-system/src/main/resources/application.yml
  pos-system/src/test/java/com/lifepill/possystem/controller/BranchSummaryControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/service/BranchSummaryServiceIMPLTest.java
Labels: documentation, enhancement, BugFIxed, New functionality

#78 Implement Additional Endpoints for Pharmacy Summary Data
  pos-system/src/main/java/com/lifepill/possystem/controller/BranchSummaryController.java
  pos-system/src/main/java/com/lifepill/possystem/dto/BranchDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/EmployerDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/EmployerWithoutImageDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/ItemCategoryDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/ItemDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/SupplierCompanyDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/SupplierDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/paginated/PaginatedResponseItemDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/AuthenticationRequestDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/BranchUpdateDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/EmployerUpdate/EmployerAllDetailsUpdateDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/EmployerUpdate/EmployerPasswordResetDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/EmployerUpdate/EmployerRecentPinUpdateDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/EmployerUpdate/EmployerUpdateAccountDetailsDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/EmployerUpdate/EmployerUpdateBankAccountDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/EmployerUpdate/EmployerUpdateDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/ItemSaveRequestCategoryDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/ItemSaveRequestDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/ItemUpdateDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/RegisterRequestDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/RequestOrderDetailsSaveDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/RequestOrderSaveDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/RequestPaymentDetailsDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/AuthenticationResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/EmployerAuthDetailsResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/ItemGetAllResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/ItemGetResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/PharmacyBranchResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/entity/BaseEntity.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Branch.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Employer.java
  pos-system/src/main/java/com/lifepill/possystem/entity/EmployerBankDetails.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Item.java
  pos-system/src/main/java/com/lifepill/possystem/entity/ItemCategory.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Order.java
  pos-system/src/main/java/com/lifepill/possystem/entity/OrderDetails.java
  pos-system/src/main/java/com/lifepill/possystem/entity/PaymentDetails.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Supplier.java
  pos-system/src/main/java/com/lifepill/possystem/entity/SupplierCompany.java
  pos-system/src/main/java/com/lifepill/possystem/entity/enums/Gender.java
  pos-system/src/main/java/com/lifepill/possystem/entity/enums/MeasuringUnitType.java
  pos-system/src/main/java/com/lifepill/possystem/entity/enums/Permission.java
  pos-system/src/main/java/com/lifepill/possystem/entity/enums/Role.java
  pos-system/src/main/java/com/lifepill/possystem/exception/AuthenticationException.java
  pos-system/src/main/java/com/lifepill/possystem/exception/BadRequestException.java
  pos-system/src/main/java/com/lifepill/possystem/exception/EntityDuplicationException.java
  pos-system/src/main/java/com/lifepill/possystem/exception/EntityNotFoundException.java
  pos-system/src/main/java/com/lifepill/possystem/exception/ForbiddenException.java
  pos-system/src/main/java/com/lifepill/possystem/exception/InsufficientItemQuantityException.java
  pos-system/src/main/java/com/lifepill/possystem/exception/InternalServerErrorException.java
  pos-system/src/main/java/com/lifepill/possystem/exception/InvalidRequestException.java
  pos-system/src/main/java/com/lifepill/possystem/exception/NotFoundException.java
  pos-system/src/main/java/com/lifepill/possystem/exception/UnauthorizedException.java
  pos-system/src/main/java/com/lifepill/possystem/exception/UnprocessableEntityException.java
  pos-system/src/main/java/com/lifepill/possystem/filter/JwtAuthFilter.java
  pos-system/src/main/java/com/lifepill/possystem/helper/SaveImageHelper.java
  pos-system/src/main/java/com/lifepill/possystem/repo/orderRepository/OrderRepository.java
  pos-system/src/main/java/com/lifepill/possystem/service/BranchSummaryService.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/BranchSummaryServiceIMPL.java
Labels: New functionality

#79 Implement Endpoint for Retrieving Summary of All Pharmacy Branches
  pos-system/Dockerfile
  pos-system/docker-compose.yml
  pos-system/pom.xml
  pos-system/src/main/java/com/lifepill/possystem/PosSystemApplication.java
  pos-system/src/main/java/com/lifepill/possystem/config/JwtService.java
  pos-system/src/main/java/com/lifepill/possystem/controller/BranchSummaryController.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/AllPharmacySummaryResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/repo/branchRepository/BranchRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/employerRepository/EmployerBankDetailsRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/employerRepository/EmployerRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/itemRepository/ItemCategoryRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/itemRepository/ItemRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/orderRepository/OrderDetailsRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/orderRepository/OrderRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/paymentRepository/PaymentRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/supplierRepository/SupplierCompanyRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/supplierRepository/SupplierRepository.java
  pos-system/src/main/java/com/lifepill/possystem/service/BranchSummaryService.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/AuthServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/BranchServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/BranchSummaryServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/EmployerServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/ItemServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/OrderServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/SupplierCompanyServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/SupplierServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/util/StandardResponse.java
  pos-system/src/test/java/com/lifepill/possystem/controller/BranchSummaryControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/repo/EmployerRepositoryTests.java
  pos-system/src/test/java/com/lifepill/possystem/repo/ItemRepositoryTest.java
  pos-system/src/test/java/com/lifepill/possystem/repo/OrderDetailsRepositoryTest.java
  pos-system/src/test/java/com/lifepill/possystem/repo/OrderRepositoryTest.java
  pos-system/src/test/java/com/lifepill/possystem/service/BranchSummaryServiceIMPLTest.java
Labels: enhancement, BugFIxed

#81 Add Unit Tests for AuthController and Cucumber Tests for Authentication Feature
  pos-system/pom.xml
  pos-system/src/main/java/com/lifepill/possystem/controller/AuthController.java
  pos-system/src/test/java/com/lifepill/possystem/controller/AuthControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/AuthStepDefinitions.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/auth.feature
Labels: BugFIxed, unit Test
