Repository Life-Pill/pharmacy-pos-main-backend, pull requests merged in 2024-05, with the labels that each got.

#83 Add Unit Tests and Resolve Issues in BranchController
  pos-system/src/main/java/com/lifepill/possystem/controller/AuthController.java
  pos-system/src/main/java/com/lifepill/possystem/service/AuthService.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/AuthServiceIMPL.java
  pos-system/src/test/java/com/lifepill/possystem/PosSystemApplicationTests.java
  pos-system/src/test/java/com/lifepill/possystem/controller/AuthControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/BranchControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/AuthStepDefinitions.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/auth.feature
Labels: BugFIxed

#84 Update CORS Policy and Filter Chain Configuration
  pos-system/.DS_Store
  pos-system/src/main/java/com/lifepill/possystem/config/ApplicationConfig.java
  pos-system/src/main/java/com/lifepill/possystem/config/CorsConfiguration.java
  pos-system/src/main/java/com/lifepill/possystem/config/SecurityConfiguration.java
  pos-system/src/main/java/com/lifepill/possystem/config/WebConfig.java
  pos-system/src/main/java/com/lifepill/possystem/config/WebMvcConfig.java
  pos-system/src/main/java/com/lifepill/possystem/filter/CorsFilter.java
  pos-system/src/main/java/com/lifepill/possystem/filter/JwtAuthFilter.java
  pos-system/src/test/java/com/lifepill/possystem/controller/BranchControllerTest.java
Labels: BugFIxed

#88 Implement Bank Details Endpoint , Resovel mvn Error and Bug Fixing
  pos-system/src/main/java/com/lifepill/possystem/controller/EmployerController.java
  pos-system/src/main/java/com/lifepill/possystem/dto/EmployerWithBankDTO.java
  pos-system/src/main/java/com/lifepill/possystem/entity/EmployerBankDetails.java
  pos-system/src/main/java/com/lifepill/possystem/repo/employerRepository/EmployerBankDetailsRepository.java
  pos-system/src/main/java/com/lifepill/possystem/service/EmployerService.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/EmployerServiceIMPL.java
  pos-system/src/test/java/com/lifepill/possystem/controller/AuthControllerTest.java
Labels: enhancement, BugFIxed, New functionality

#89 Add Unit Tests for CashierController and EmployerController
  pos-system/pom.xml
  pos-system/src/test/java/com/lifepill/possystem/controller/BranchManagerControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/CashierControllerTests.java
  pos-system/src/test/java/com/lifepill/possystem/controller/EmployerControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/AuthSteps.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/supplier/SupplierStepDefinitions.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/supplier/supplier.feature
  pos-system/src/test/java/com/lifepill/possystem/cucumberglue/CucumbertestRunner.java
  pos-system/src/test/java/com/lifepill/possystem/service/EmployerServiceTest.java
  pos-system/src/test/resources/application-dev.yml
  pos-system/src/test/resources/application-qa.yml
  pos-system/src/test/resources/application.yml
Labels: BugFIxed, unit Test

#90 Add Comprehensive Unit Tests
  pos-system/pom.xml
  pos-system/src/main/java/com/lifepill/possystem/controller/EmployerController.java
  pos-system/src/test/java/com/lifepill/possystem/config/CucumberRunnerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/BranchManagerControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/CashierControllerTests.java
  pos-system/src/test/java/com/lifepill/possystem/controller/EmployerControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/EmployerControllerTests.java
  pos-system/src/test/java/com/lifepill/possystem/controller/ItemCategoryControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/ItemControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/OrderControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/OwnerControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/SupplierCompanyControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/SupplierControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/AuthStepDefinitions.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/AuthSteps.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/supplier/SupplierStepDefinitions.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/supplier/supplier.feature
  pos-system/src/test/java/com/lifepill/possystem/service/BranchSummaryServiceIMPLTest.java
  pos-system/src/test/java/com/lifepill/possystem/service/EmployerServiceImplTest.java
  pos-system/src/test/java/com/lifepill/possystem/service/ItemServiceIMPLTest.java
  pos-system/src/test/java/com/lifepill/possystem/service/SupplierCompanyServiceIMPLTest.java
  pos-system/src/test/java/com/lifepill/possystem/service/SupplierServiceIMPLTest.java
Labels: BugFIxed, unit Test

#91 Add Comprehensive Unit Tests
  pos-system/src/test/java/com/lifepill/possystem/cucumber/AuthStepDefinitions.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/AuthSteps.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/auth.feature
  pos-system/src/test/java/com/lifepill/possystem/cucumber/supplier/SupplierStepDefinitions.java
  pos-system/src/test/java/com/lifepill/possystem/cucumber/supplier/supplier.feature
  pos-system/src/test/java/com/lifepill/possystem/cucumberglue/CucumbertestRunner.java
Labels: BugFIxed

#93 Fix Issue with Employer ID in Response
  pos-system/Jenkinsfile
  pos-system/src/main/java/com/lifepill/possystem/controller/BranchSummaryController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/EmployerController.java
  pos-system/src/main/java/com/lifepill/possystem/entity/enums/Role.java
  pos-system/src/main/java/com/lifepill/possystem/repo/employerRepository/EmployerRepository.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/EmployerServiceIMPL.java
Labels: BugFIxed

#94 Add Item Retrieval by Name and Enhance Item Data Response
  pos-system/src/main/java/com/lifepill/possystem/controller/ItemCategoryController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/ItemController.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/ItemSaveRequestCategoryDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/ItemSaveRequestDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/ItemGetAllResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/ItemGetResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Branch.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Item.java
  pos-system/src/main/java/com/lifepill/possystem/repo/itemRepository/ItemRepository.java
  pos-system/src/main/java/com/lifepill/possystem/service/ItemService.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/EmployerServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/ItemServiceIMPL.java
Labels: enhancement, BugFIxed, New functionality

#97 Integrate SonarQube for Code Quality Analysis
  .github/workflows/build.yaml
Labels: enhancement

#98 Update pom.xml for SonarQube Integration
  pos-system/pom.xml
Labels: BugFIxed

#99 Add Endpoints for Retrieving Item Details by ID
  pos-system/src/main/java/com/lifepill/possystem/controller/ItemController.java
  pos-system/src/main/java/com/lifepill/possystem/dto/ItemCategoryDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/ItemDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/ItemGetIdResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/repo/employerRepository/EmployerRepository.java
  pos-system/src/main/java/com/lifepill/possystem/service/ItemService.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/ItemServiceIMPL.java
Labels: New functionality

#100 Fix StackOverflowError in Entity toString Methods
  pos-system/src/main/java/com/lifepill/possystem/entity/Item.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Supplier.java
Labels: BugFIxed

#101 Refactor Item Details Endpoints and Clean Code
  pos-system/src/main/java/com/lifepill/possystem/advisor/AppWideExceptionHandler.java
  pos-system/src/main/java/com/lifepill/possystem/config/ApplicationConfig.java
  pos-system/src/main/java/com/lifepill/possystem/config/JwtService.java
  pos-system/src/main/java/com/lifepill/possystem/config/SecurityConfiguration.java
  pos-system/src/main/java/com/lifepill/possystem/config/WebMvcConfig.java
  pos-system/src/main/java/com/lifepill/possystem/controller/AuthController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/BranchController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/BranchManagerController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/BranchSummaryController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/CashierController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/EmployerController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/ItemCategoryController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/ItemController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/NoticesController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/OrderController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/OwnerController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/SupplierCompanyController.java
  pos-system/src/main/java/com/lifepill/possystem/controller/SupplierController.java
  pos-system/src/main/java/com/lifepill/possystem/dto/BranchDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/EmployerBankDetailsDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/EmployerDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/EmployerWithBankDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/GroupedOrderDetails.java
  pos-system/src/main/java/com/lifepill/possystem/dto/ItemDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/RequestOrderDetailsSaveDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/requestDTO/RequestOrderSaveDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/ItemGetIdResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/ItemGetResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/ItemGetResponseWithoutSupplierDetailsDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/OrderResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/dto/responseDTO/PharmacyBranchResponseDTO.java
  pos-system/src/main/java/com/lifepill/possystem/entity/BaseEntity.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Employer.java
  pos-system/src/main/java/com/lifepill/possystem/entity/Supplier.java
  pos-system/src/main/java/com/lifepill/possystem/filter/JwtAuthFilter.java
  pos-system/src/main/java/com/lifepill/possystem/repo/employerRepository/EmployerRepository.java
  pos-system/src/main/java/com/lifepill/possystem/repo/orderRepository/OrderDetailsRepository.java
  pos-system/src/main/java/com/lifepill/possystem/service/BranchService.java
  pos-system/src/main/java/com/lifepill/possystem/service/ItemService.java
  pos-system/src/main/java/com/lifepill/possystem/service/MedicineFindingService.java
  pos-system/src/main/java/com/lifepill/possystem/service/OrderService.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/BranchServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/ItemServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/OrderServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/SupplierCompanyServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/SupplierServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/util/mappers/ItemMapper.java
  pos-system/src/test/java/com/lifepill/possystem/controller/BranchManagerControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/BranchSummaryControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/CashierControllerTests.java
  pos-system/src/test/java/com/lifepill/possystem/controller/ItemControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/OwnerControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/controller/SupplierCompanyControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/repo/ItemRepositoryTest.java
  pos-system/src/test/java/com/lifepill/possystem/repo/OrderDetailsRepositoryTest.java
  pos-system/src/test/java/com/lifepill/possystem/service/EmployerServiceImplTest.java
  pos-system/src/test/java/com/lifepill/possystem/service/EmployerServiceTest.java
  pos-system/src/test/java/com/lifepill/possystem/service/ItemServiceIMPLTest.java
Labels: documentation, enhancement, BugFIxed

#102 Implement Update Employer Bank Account Details Endpoint
  pos-system/src/main/java/com/lifepill/possystem/controller/EmployerController.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/EmployerServiceIMPL.java
  pos-system/src/test/java/com/lifepill/possystem/config/TestConfiguration.java
  pos-system/src/test/java/com/lifepill/possystem/controller/EmployerControllerTest.java
  pos-system/src/test/java/com/lifepill/possystem/service/EmployerServiceImplTest.java
Labels: BugFIxed

#103 Implement Order Details Endpoints
  pos-system/src/main/java/com/lifepill/possystem/controller/OrderController.java
  pos-system/src/main/java/com/lifepill/possystem/service/OrderService.java
  pos-system/src/main/java/com/lifepill/possystem/service/impl/OrderServiceIMPL.java
  pos-system/src/main/java/com/lifepill/possystem/util/mappers/OrderMapper.java
  pos-system/src/test/java/com/lifepill/possystem/controller/OrderControllerTest.java
Labels: New functionality

#104 Update Docker Configuration for Spring Boot Application
  pos-system/Dockerfile
  pos-system/docker-compose.yml
Labels: enhancement

#105 Add SQL Queries for Medicine Finding and Implement Authentication
  pos-system/src/main/java/com/lifepill/possystem/advisor/AppWideExceptionHandler.java
  pos-system/src/main/java/com/lifepill/possystem/config/SecurityConfiguration.java
  pos-system/src/main/resources/application.yml
  pos-system/src/main/resources/sql/scripts.sql
Labels: database enchancement
